const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('petApi', {
  load: () => ipcRenderer.invoke('load'),
  setIgnoreMouse: ignore => ipcRenderer.send('set-ignore', ignore),
  showMenu: petName => ipcRenderer.send('menu', petName),
  onShow: fn => ipcRenderer.on('show', (_event, value) => fn(value)),
  onCursor: fn => ipcRenderer.on('cursor', (_event, point) => fn(point)),
  onFeatures: fn => ipcRenderer.on('features', (_event, features) => fn(features)),
  onActivity: fn => ipcRenderer.on('activity', (_event, activity) => fn(activity)),
  touched: () => ipcRenderer.send('pet-touched'),
  onSize: fn => ipcRenderer.on('size', (_event, size) => fn(size)),
  onPresence: fn => ipcRenderer.on('presence', (_event, online) => fn(online)),
  onRemote: fn => ipcRenderer.on('remote', (_event, message) => fn(message)),
  onScreens: fn => ipcRenderer.on('screens', (_event, screens) => fn(screens)),
  onResync: fn => ipcRenderer.on('resync', () => fn()),
  onUpdateReady: fn => ipcRenderer.on('update-ready', (_event, version) => fn(version)),
  restartUpdate: () => ipcRenderer.send('restart-update'),
  onWeather: fn => ipcRenderer.on('weather', (_event, kind) => fn(kind)),
  onToday: fn => ipcRenderer.on('today', (_event, today) => fn(today)),
  onFocus: fn => ipcRenderer.on('focus', (_event, on) => fn(on)),
  onFocusDone: fn => ipcRenderer.on('focus-done', () => fn()),
  onAskContinue: fn => ipcRenderer.on('ask-continue', () => fn()),
  startFocus: () => ipcRenderer.send('start-focus'),
  onPhoto: fn => ipcRenderer.on('photo', () => fn()),
  savePhoto: bytes => ipcRenderer.send('save-photo', bytes),
  onTease: fn => ipcRenderer.on('tease', (_event, name) => fn(name)),
  sendVisit: (type, pet) => ipcRenderer.send('visit-send', { type, pet }),
  reportVisits: state => ipcRenderer.send('visit-state', state),
  onVisitPets: fn => ipcRenderer.on('visit-pets', (_event, allowed) => fn(allowed)),
  onCallHome: fn => ipcRenderer.on('call-home', (_event, name) => fn(name)),
  onSendHome: fn => ipcRenderer.on('send-home', (_event, name) => fn(name)),
  onTest: fn => ipcRenderer.on('test', (_event, test) => fn(test)),
  onSay: fn => ipcRenderer.on('say', (_event, text) => fn(text)),
  onPerch: fn => ipcRenderer.on('perch', (_event, ledge) => fn(ledge)),
  onCpuHot: fn => ipcRenderer.on('cpu-hot', (_event, hot) => fn(hot)),
  onSitReminder: fn => ipcRenderer.on('sit-reminder', () => fn()),
});
